spring:
  datasource:
    url: ${LOCAL_DB_URL:${DB_URL:jdbc:postgresql://localhost:5432/neuralhealer}}
    username: ${LOCAL_DB_USERNAME:${DB_USERNAME:postgres}}
    password: ${LOCAL_DB_PASSWORD:${DB_PASSWORD:postgres}}
  jpa:
    hibernate:
      ddl-auto: update # Automatic updates for dev convenience
    show-sql: false

logging:
  level:
    root: WARN
    "[com.neuralhealer.backend]": DEBUG
    "[com.neuralhealer.backend.feature.email.gmail.EmailQueueProcessor]": INFO
    "[org.hibernate.SQL]": WARN
    "[org.hibernate.type.descriptor.sql.BasicBinder]": WARN
    "[org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver]": ERROR
    "[org.springframework.web.cors.DefaultCorsProcessor]": ERROR
    "[org.springframework.security.web.FilterChainProxy]": WARN
