spring:
  datasource:
    url: ${GLOBAL_DB_URL}
    username: ${GLOBAL_DB_USERNAME}
    password: ${GLOBAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # Never auto-migrate in prod
    show-sql: false

neuralhealer:
  security:
    cookie:
      secure: true
      same-site: Strict

logging:
  level:
    "[com.neuralhealer.backend]": INFO
    "[org.springframework.security]": INFO
    "[org.hibernate.SQL]": ERROR
