package com.neuralhealer.backend.model.entity;

import com.neuralhealer.backend.model.enums.EngagementStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a professional engagement between a doctor and a patient.
 * Maps to: engagements table
 * 
 * Tracks the lifecycle: PENDING -> ACTIVE -> ENDED (or CANCELLED/ARCHIVED)
 */
@Entity
@Table(name = "engagements")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamicUpdate
public class Engagement {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    // Human-readable ID (e.g., ENG-2024-001) generated by DB trigger/sequence
    @Column(name = "engagement_id", insertable = false, updatable = false)
    private String engagementId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false)
    private User doctor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false)
    private User patient;

    @Enumerated(EnumType.STRING)
    @Column(columnDefinition = "engagement_status")
    private EngagementStatus status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "access_rule_name")
    private EngagementAccessRule accessRule;

    @Column(name = "start_at")
    private LocalDateTime startAt;

    @Column(name = "end_at")
    private LocalDateTime endAt;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
